### ISSUE TITLE
Asynchronous call

### ISSUE THREAD

**Issue by clayrisser** [ziolko/babel-plugin-auto-await#1]
How do you explicitly call a function asynchronously instead of waiting for it. Here is my suggestion (stealing this syntax from golang).

```js
async () => {
  new Promise (r => setTimeout(r, 5000)); // wait 5 seconds
  go new Promise (r => setTimeout(r, 5000)); // run in parallel
}
```

**Comment by ziolko** [comment]
Thank you @codejamninja for raising that. Introducing new language constructs causes issues with code editors and other tools parsing source code so I'd rather not do that.

Notice that regular (not `async`) functions are not transformed by this plugin. You can take advantage of this and define a helper function:
```js
const run = fn => [fn()];
```

Then you can use this function as follows:


```js
async () => {
  new Promise (r => setTimeout(r, 5000)); // wait 5 seconds
  run(() => new Promise (r => setTimeout(r, 5000))); // run in parallel
}
```

You can even get the promise taking advantage of the destructive assignment syntax
```js
const [promise] = run(() => new Promise (r => setTimeout(r, 5000))); // run in parallel
```

**Comment by clayrisser** [comment]
Cool, thanks
