### ISSUE TITLE
shouldn't it also make all functions async?

### ISSUE THREAD

**Issue by andreineculau** [ziolko/babel-plugin-auto-await#3]
consider this example

```js
let foo = function() {
  someAsyncFunction();
}
foo();
```

this code will be left untouched, but I expected `let foo = async function` and `await someAsyncFunction`. `await foo();` is somewhat debatable because of lack of context in my example - based on whether it's getting called in top-level or not.

fwiw the reason for my expectation is the premise of the plugin "Write JS code as if it was synchronous"

**Comment by andreineculau** [comment]
I can see how the expectation can cause problems e.g. `items = _.map(items, function(item) {...})` becomes unusable because `items` becomes an array of promises, etc etc

I'm mostly asking if you have given it any thought.

**Comment by ziolko** [comment]
Thanks for raising this @andreineculau. I thought about this, but this becomes problematic when you work with any external library. As you've noticed they often accept only synchronous callbacks and I'd be a nightmare to work with them :)

Hope this helps,
Mateusz
